### ISSUE TITLE
Setting to reduce logging only to errors?

### ISSUE THREAD

**Issue by sunrez** [TriliumNext/trilium#1589]
Thanks for this application I've been using it a lot recently for logging DevOps related work and it's been helpful.

Is there a way to get trilium to only log on errors but not GET / POST messages?  My log is filled with messages such as:

Jan 28 19:01:35 notes trilium[3509]: Slow GET /api/similar-notes/AqHGDVn3sxzt took 28ms
Jan 28 19:01:36 notes trilium[3509]: GET /api/script/startup took 2ms
Jan 28 19:01:36 notes trilium[3509]: POST /api/tree/load took 1ms
.
.
.

I tried to to comment out the function info in /src/log.js but then trilium failed to start-up:

Jan 28 18:59:16 notes trilium[3487]: sync failed: Cannot read property 'length' of null
Jan 28 18:59:16 notes trilium[3487]: stack: TypeError: Cannot read property 'length' of null
Jan 28 18:59:16 notes trilium[3487]:     at Object.getRowOrNull (/opt/trilium-linux-x64-server/src/services/sql.js:83:16)
Jan 28 18:59:16 notes trilium[3487]:     at getEntity (/opt/trilium-linux-x64-server/src/services/repository.js:26:21)
Jan 28 18:59:16 notes trilium[3487]:     at Object.getOption (/opt/trilium-linux-x64-server/src/services/repository.js:84:12)
Jan 28 18:59:16 notes trilium[3487]:     at Object.getOption (/opt/trilium-linux-x64-server/src/services/options.js:2:44)
Jan 28 18:59:16 notes trilium[3487]:     at get (/opt/trilium-linux-x64-server/src/services/sync_options.js:14:70)
Jan 28 18:59:16 notes trilium[3487]:     at Object.isSyncSetup (/opt/trilium-linux-x64-server/src/services/sync_options.js:20:32)
Jan 28 18:59:16 notes trilium[3487]:     at /opt/trilium-linux-x64-server/src/services/sync.js:28:30
Jan 28 18:59:16 notes trilium[3487]:     at Object.doExclusively (/opt/trilium-linux-x64-server/src/services/sync_mutex.js:13:22)
Jan 28 18:59:16 notes trilium[3487]:     at async sync (/opt/trilium-linux-x64-server/src/services/sync.js:27:16)

**Comment by zadam** [comment]
Hi, no, it's not possible. "non-error" log messages are often need to provide context for the debugging of the actual errors ...

**Comment by alpe12** [comment]
@zadam 
Still should be an option.
I'm discarding every message that contains /api/ as a workaround.

**Comment by meichthys** [comment]
[Trilium has entered maintenance mode](https://github.com/zadam/trilium/issues/4620#issuecomment-2094495698). Future enhancements will be addressed in TrilumNext: https://github.com/TriliumNext/trilium/issues/5002

**Comment by eliandoran** [comment]
Log verbosity tuning is a low-value config knob; standard syslog filtering handles this externally.
