### ISSUE TITLE
Upgrade broke my Docker installment

### ISSUE THREAD

**Issue by zDEFz** [TriliumNext/Trilium#1747]
It isn't enough to just re-pull from the docker hub and restart the containers. Here is what I did... and failed!
Prior upgrades worked.

I tried to upgrade from **0.45.10** to the **v0.46.5 release**
To note is that priorly, I could upgrade without trouble.

### Steps done:

**Resulted in same version**
`docker pull zadam/trilium; docker stop triliumcontainer; docker run triliumcontainer`
OR
`docker pull zadam/trilium; docker restart triliumcontainer`

**Resulted in bad gateway**
`docker pull zadam/trilium; docker stop triliumcontainer; docker rm triliumcontainer; sudo docker run -t --name triliumcontainer --restart always -i -d -p 127.0.0.1:8100:8100 -v ~/trilium-pianostudy:/root/trilium-data zadam/trilium`

**Resulted in folder of the new folder being empty**
`docker pull zadam/trilium; docker stop triliumcontainer; docker rm triliumcontainer; sudo docker run -t --name triliumcontainer --restart always -i -d -p 127.0.0.1:8100:8100 -v ~/trilium-pianostudy-upgraded:/root/trilium-data zadam/trilium`

**Comment by bhammack** [comment]
I encountered the same issue this morning. Ouroboros updated my stack to the the `latest` docker image and it acted as if it was entirely new -- requesting that I re-setup my instance. My solution was to restart the stack using the `0.45-latest` tag, which restored it to a working state.

**Comment by zDEFz** [comment]
> I encountered the same issue this morning. Ouroboros updated my stack to the the `latest` docker image and it acted as if it was entirely new -- requesting that I re-setup my instance. My solution was to restart the stack using the `0.45-latest` tag, which restored it to a working state.

Pro tip:

Have all your containers running on your local machine. Sync them with the server.
Whatever happens, the target system will always take the newest version, in your case your localhost installation.
That and have snapshots of your server. I use vultr and it's easy to setup.

That's how I recovered.

**Comment by klausenbusk** [comment]
The issue seems to be caused by this change: https://github.com/zadam/trilium/commit/4fd9e7f14f29dcf91ff6a2d26bd1ef24c2e6d86a. In my case I fixed the issue by running `docker exec -t -i -u root trilium chown -R node:node /root/trilium-data` first and then changing container-dir to `/home/node/trilium-data`

**Comment by zDEFz** [comment]
> The issue seems to be caused by this change: [4fd9e7f](https://github.com/zadam/trilium/commit/4fd9e7f14f29dcf91ff6a2d26bd1ef24c2e6d86a). In my case I fixed the issue by running `docker exec -t -i -u root trilium chown -R node:node /root/trilium-data` first and then changing container-dir to `/home/node/trilium-data`

What does that do? And why do I suddenly have to change the folder where my trilium is located?
Dude, that's like, confusing.

Would you have todo `mkdir /home; mkdir/home/node; mv /root/trilium-container/ /home/node/` ?
That would be so annoying! Please revert!

**Comment by klausenbusk** [comment]
> Now we have to move all our installation to /home/node/ ?
> **That would be so annoying! Please revert!**
> **I don't have the /home/node/ directory at all!**

You don't need to move anything, you just need to fix the permissions and change the mount path used inside the container (CONTAINER-DIR). Are you running v0.46?

**Comment by zadam** [comment]
@klausenbusk thanks for looking into this. I added your instructions to the release page.

**Comment by zhdenny** [comment]
Was scratching my head on this one for like 5 minutes before I decided to come here and read recent issues. Glad someone has a solution. I really hope changes like this do not become a common occurance.

**Comment by zDEFz** [comment]
> docker exec -t -i -u root trilium chown -R node:node /root/trilium-data

dude, you gotta be more clear...

Instead of doing that...

`docker container stop yourcontainer; docker container rm yourcontainer; sudo docker run -t --name pianotrilium --restart always -i -d -p 127.0.0.1:8100:8100 -v ~/trilium-pianostudy:/home/node/trilium-data`

**Comment by zDEFz** [comment]
This was complicated. Please no more of this...

**Comment by v587ygq** [comment]
if you use `docker-compose.yml`, you can add a line to solve it:
```
user: 0:0
```

**Comment by BeecherNetworks** [comment]
So just to be clear, I need to do the following:

1. docker exec -t -i -u root trilium chown -R node:node /root/trilium-data
2. Change './data:/root/trilium-data' to './data:/home/node/trilium-data'
3. docker-compose pull
4. docker-compose up -d

Is that right?

**Comment by patrickjm** [comment]
@BeecherNetworks What you did might be right, what worked for me was:

1. Stop trilium container
2. Change './data:/root/trilium-data' to './data:/home/node/trilium-data' in docker-compose.yml
3. On my outer machine (not inside docker), `chmod -R 0777 <my trilium data dir>`
4. `docker-compose up -d`

I didn't have to `docker-compose pull`, but I was using a fresh install, so you may still need to.

**Comment by jkaplon** [comment]
I updated wiki pages for [Docker setup](https://github.com/zadam/trilium/wiki/Docker-server-installation) and [Apache proxy setup](https://github.com/zadam/trilium/wiki/Apache-proxy-setup) to reflect the switch from root-user to node-user in the container.

I was hoping to bundle them up into a pull-request, but I guess that's not how editing works in the wiki section.

**Comment by terafo** [comment]
@jkaplon setup isn't working with this.
`internal/fs/utils.js:269
    throw err;
    ^

Error: EACCES: permission denied, mkdir '/home/node/trilium-data/log'
    at Object.mkdirSync (fs.js:921:3)
    at Object.<anonymous> (/usr/src/app/src/services/log.js:7:8)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/src/app/src/app.js:1:13)
    at Module._compile (internal/modules/cjs/loader.js:1015:30) {
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/home/node/trilium-data/log'
}`

**Comment by zadam** [comment]
@terafo looks like a permission problem. This should help:

```
chmod -R 0777 /home/node/trilium-data
```

**Comment by terafo** [comment]
@zadam yes, but container stops before I have a chance to do that.

**Comment by zadam** [comment]
I meant to execute this in the host environment (use whatever host path is bound to guest's `/home/node/trilium-data`)

**Comment by terafo** [comment]
@zadam thanks, it works!

**Comment by klausenbusk** [comment]
> @terafo looks like a permission problem. This should help:
> 
> ```
> chmod -R 0777 /home/node/trilium-data
> ```

Please don't recommend that kind of solutions! You should never make files on a Linux system world writable, never! :)

The correct command to execute from the host in this case would be:
```sh
$ chown -R 1000:1000 /path/to/trilium-data
```

**Comment by zDEFz** [comment]
Guys, please implement update functionalities that don't involve that knowledge...

**Comment by mursilsayed** [comment]
> > @terafo looks like a permission problem. This should help:
> > ```
> > chmod -R 0777 /home/node/trilium-data
> > ```
> 
> Please don't recommend that kind of solutions! You should never make files on a Linux system world writable, never! :)
> 
> The correct command to execute from the host in this case would be:
> 
> ```shell
> $ chown -R 1000:1000 /path/to/trilium-data
> ```

How do you know the user id for node user is 1000? It is 1000 in most cases but it can be anything.

**Comment by klausenbusk** [comment]
> How do you know the user id for node user is 1000? It is 1000 in most cases but it can be anything.

See: https://github.com/nodejs/docker-node/blob/a8494b1676216bfe274073993016da0c2e0bfcdd/12/alpine3.11/Dockerfile#L5-L6

**Comment by rsheftel** [comment]
> 2\. Change './data:/root/trilium-data' to './data:/home/node/trilium-data' in docker-compose.yml

How do I do this step?

`Change './data:/root/trilium-data' to './data:/home/node/trilium-data' in docker-compose.yml
`
Where is the docker-compose.yml file located? I could not find it in the trillium-data directory

**Comment by patrickjm** [comment]
@rsheftel Thats only if you're using docker compose. Do you mind posting the command you used to start trilium?

**Comment by zDEFz** [comment]
> @rsheftel Thats only if you're using docker compose. Do you mind posting the command you used to start trilium?

Shows clearly a mandatory requirement: No need to use docker-compose - and a guided process for updating.

**Comment by rsheftel** [comment]
@patrickjm here are the commands I try and what they do. My original 0.45.8 works, but I cannot get 0.46.6 to work

I pull the dock images like this:
	
```
docker pull zadam/trilium:0.45.8
docker pull zadam/trilium:0.46.6
```	

When I run the 0.45.8 with this command (the one from the wiki prior to the 0.46 update) everything works fine and I can access my notes:
	
```
docker run -d -p 0.0.0.0:8080:8080 -v ~/trilium-data:/root/trilium-data zadam/trilium:0.45.8	

$ docker ps
CONTAINER ID   IMAGE                  COMMAND                  CREATED        STATUS        PORTS                    NAMES
c111523e0f3a   zadam/trilium:0.45.8   "docker-entrypoint.s…"   22 hours ago   Up 22 hours   0.0.0.0:8080->8080/tcp   upbeat_bassi
```	

When I run the 0.46.6 with the same command, it runs but does not find my documents.db and shows the prompt for a new install
	
```
docker run -d -p 0.0.0.0:8080:8080 -v ~/trilium-data:/root/trilium-data zadam/trilium:0.46.6
	
$ docker ps
CONTAINER ID   IMAGE                  COMMAND                  CREATED          STATUS          PORTS                    NAMES
52892b67ed78   zadam/trilium:0.46.6   "docker-entrypoint.s…"   44 seconds ago   Up 37 seconds   0.0.0.0:8080->8080/tcp   magical_cerf
```

![image](https://user-images.githubusercontent.com/11539619/113418184-fc293780-9392-11eb-88e8-5089bdd9d521.png)

When I run the 0.46.6 with the new command in the current wiki the service will start and then a moment later shut down

```
docker run -d -p 0.0.0.0:8080:8080 -v ~/trilium-data:/home/node/trilium-data zadam/trilium:0.46.6

$ docker ps
CONTAINER ID   IMAGE                  COMMAND                  CREATED         STATUS         PORTS                    NAMES
aa699ca5eb1a   zadam/trilium:0.46.6   "docker-entrypoint.s…"   6 seconds ago   Up 3 seconds   0.0.0.0:8080->8080/tcp   amazing_mcnulty

$ docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
```

**Comment by zDEFz** [comment]
You might end up being told that you haven't read properly - either docker documentation or this thread.

I don't recommend to update at the current point of time, cause the UI got harder to use in half-sized windows.
Anyways, so many people having problems does emphasize that even the docker installment has to be as simple as can be.

**Comment by klausenbusk** [comment]
> When I run the 0.46.6 with the new command in the current wiki the service will start and then a moment later shut down

Probably due to wrong permissions.

Try running:
```sh
$ docker run -d -p 0.0.0.0:8080:8080 -v ~/trilium-data:/root/trilium-data --name trilium zadam/trilium:0.46.6
$ docker exec -t -i -u root trilium chown -R node:node /root/trilium-data
$ docker stop trilium
$ docker run -d -p 0.0.0.0:8080:8080 -v ~/trilium-data:/home/node/trilium-data zadam/trilium:0.46.6
```

**Comment by rsheftel** [comment]
@klausenbusk if I do this, will 0.45.8 stop working or will both 0.45.8 and 0.46.6 work depending on which one I want to launch? I am not sure I want to upgrade yet, so before I do this just want to know if it is a "no going back" path. thanks

> Try running:
> 
> ```shell
> $ docker run -d -p 0.0.0.0:8080:8080 -v ~/trilium-data:/root/trilium-data --name trilium zadam/trilium:0.46.6
> $ docker exec -t -i -u root trilium chown -R node:node /root/trilium-data
> $ docker stop trilium
> $ docker run -d -p 0.0.0.0:8080:8080 -v ~/triliu
> ```

**Comment by klausenbusk** [comment]
> @klausenbusk if I do this, will 0.45.8 stop working or will both 0.45.8 and 0.46.6 work depending on which one I want to launch?

v0.46.6 contains migrations not part of v0.45.8, so you can't downgrade.

**Comment by zadam** [comment]
> v0.46.6 contains migrations not part of v0.45.8, so you can't downgrade.

That's true, but simple backup of `document.db` before the upgrade allows you to go back. In fact Trilium does the automatically (creates `backup/backup-before-migration.db`).

**Comment by DannyFL** [comment]
Thank you everyone for your help! The part that really worked for me was:

`
$ docker run -d -p 0.0.0.0:8080:8080 -v ~/trilium-data:/root/trilium-data --name trilium zadam/trilium:0.46.6
$ docker exec -t -i -u root trilium chown -R node:node /root/trilium-data
$ docker stop trilium
$ docker run -d -p 0.0.0.0:8080:8080 -v ~/trilium-data:/home/node/trilium-data zadam/trilium:0.46.6
`

**Comment by eliandoran** [comment]
Since the issue is from 2021, assuming it got fixed at some point.
