### ISSUE TITLE
Trilium won't start when /tmp is mounted with noexec

### ISSUE THREAD

**Issue by drzero42** [TriliumNext/Trilium#2207]
Trilium version: 0.47.8
Log-file is empty.
OS: Ubuntu 20.04.3
Trilium was installed with the .deb from GitHub release.

While performing CIS hardening of the machine for Level 1 workstation, one of the steps is to ensure /tmp is a separate mount from /, and that it is mounted with the noexec option, to protect against software being able to download arbitrary code and executing. After I performed this step, Trilium will no longer start. When I remount /tmp without noexec, Trilium starts just fine.

When /tmp is mounted with noexec, this output is given when starting Trilium from a terminal:

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /tmp/.org.chromium.Chromium.v3wLjx: failed to map segment from shared object
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2073)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at bindings (/usr/lib/trilium/resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/usr/lib/trilium/resources/app.asar/node_modules/better-sqlite3/lib/database.js:9:24)
```

**Comment by eliandoran** [comment]
Now Trilium uses a subdirectory of its data directory as `tmp`, so it should work out of the box.
