### ISSUE TITLE
ERROR: Failed to deserialize sync response: Option "documentSecret" doesn't exist

### ISSUE THREAD

**Issue by rax-rstark** [TriliumNext/Trilium#2290]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a bug report that matches the one I want to file, without success.

### Trilium Version

0.48.3

### What operating system are you using?

macOS

### What is your setup?

Local + server sync

### Operating System Version

12.0.1

### Expected Behavior

I would expect that server sync would be able to resume in the event that a remote docker container is killed and then restarted for any reason.

### Actual Behavior

When I setup sync to a remote server running Ubuntu 20.04 and a docker/ngnix setup, initially it works as expected. The docker image is killed by oom (a separate issue to resolve), and once restarted, the client in now unable to sync with the follow local log file messages:

```
10:33:20.026 Received request to trigger sync now.
10:33:20.026 Sending message to all clients: {"type":"sync-pull-in-progress","lastSyncedPush":44633}
10:33:20.142 sync failed: Request to POST https://trill.morphium.org//api/login/sync failed, error: 500 Internal Server Error
stack: Error: Request to POST https://trill.morphium.org//api/login/sync failed, error: 500 Internal Server Error
    at generateError (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/request.js:191:12)
    at ClientRequest.<anonymous> (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/request.js:62:28)
    at ClientRequest.emit (events.js:315:20)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6816)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
    at SimpleURLLoaderWrapper.callbackTrampoline (internal/async_hooks.js:131:14)
10:33:20.142 Slow 200 POST /api/sync/now with 129 bytes took 116ms
10:33:20.143 ERROR: Failed to deserialize sync response: Option "documentSecret" doesn't exist
```

And I see the corresponding message from the remote sync server:

```
15:33:32.825 ERROR: post /api/login/sync threw exception: Error: Option "documentSecret" doesn't exist
    at Object.getOption (/usr/src/app/src/services/options.js:7:15)
    at loginSync (/usr/src/app/src/routes/api/login.js:39:36)
    at Function.cb (/usr/src/app/src/routes/routes.js:145:34)
    at Function.sqliteTransaction (/usr/src/app/node_modules/better-sqlite3/lib/methods/transaction.js:65:24)
    at Object.transactional (/usr/src/app/src/services/sql.js:242:52)
    at /usr/src/app/src/routes/routes.js:147:44
    at /usr/src/app/node_modules/cls-hooked/context.js:118:13
    at Namespace.run (/usr/src/app/node_modules/cls-hooked/context.js:97:5)
    at Namespace.runAndReturn (/usr/src/app/node_modules/cls-hooked/context.js:117:8)
    at Object.init (/usr/src/app/src/services/cls.js:5:22)
```

The only workaround I have found so far is to delete the contents of `~/trilium-data/` and start over.

**Comment by zadam** [comment]
Thanks for the logs.

It appears that the database is completely blank. The only explanation I can think of is that you didn't mount a volume from the host system into the container so Trilium saved data within the container and thus when container crashed it took down all the data as well.

**Comment by eliandoran** [comment]
@zadam 's explanation should suffice.
