### ISSUE TITLE
(Bug report) Docker image latest version behind this repo

### ISSUE THREAD

**Issue by surajsharma** [TriliumNext/Trilium#2358]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a bug report that matches the one I want to file, without success.

### Trilium Version

0.48.6

### What operating system are you using?

Other (specify below)

### What is your setup?

Local + server sync

### Operating System Version

macOs 11.6 / Linux

### Expected Behavior

Two instances of the app, one running locally cloned repo with `npm run start-server` and the other an docker image on Azure app service from an authenticated docker hub account pulling `zadam/trilium:latest` should be the same version and should sync, as they used to until a few days back.	

### Actual Behavior

The docker image running on Azure is version 0.48.5 while the local instance is the latest 0.48.6, causing the sync to break, with the error: 

`Sync failed: Request to PUT http://***/api/sync/update failed, error: 500 Internal Server Error` on the frontend

and the following is the output of the log on the local instance when i try to sync

```
Received request to trigger sync now.
Sending message to all clients: {"type":"sync-pull-in-progress","lastSyncedPush":0}
sync failed: Request to PUT http://***/api/sync/update failed, error: 500 Internal Server Error
stack: Error: Request to PUT http://***/api/sync/update failed, error: 500 Internal Server Error
    at generateError (/Users/admin/*xxx*/trilium/src/services/request.js:191:12)
    at ClientRequest.<anonymous> (/Users/admin/*xxx*/trilium/src/services/request.js:62:28)
    at ClientRequest.emit (events.js:314:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:640:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at Socket.socketOnData (_http_client.js:509:22)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:303:12)
    at readableAddChunk (_stream_readable.js:279:9)
    at Socket.Readable.push (_stream_readable.js:218:10)
Slow 200 POST /api/sync/now with 129 bytes took 1441ms
ERROR: Failed to deserialize sync response: table entity_changes has no column named changeId
```

**Comment by zadam** [comment]
Hello, I just pushed correct tags. CI build of docker image for 0.48.6 broke so it had to be done differently which caused lack of retagging.

(using `latest` tag is generally not recommended, though)

**Comment by surajsharma** [comment]
thank you

> (using `latest` tag is generally not recommended, though)
why? and what do you recommend i do instead for the same effect?

**Comment by zadam** [comment]
There's many articles about this topic on web, first reasonable one I found is [this](https://vsupalov.com/docker-latest-tag/)

I would recommend to use `0.48-latest`.

> btw, both instances are now the same version but it still isn't syncing, getting the same error

Could you please include the server log? That should contain more details about the failure.

**Comment by capi** [comment]
Something is still strange with the docker-tags:
1. `0.48.6-docker`, it's the only one with the `-docker` suffix
2. `0.48-latest` does not match digest with `0.48.6-docker`

![image](https://user-images.githubusercontent.com/254852/142742110-2a067b55-f5b6-4b4a-b138-9fb39aed04e9.png)

**Comment by surajsharma** [comment]
> > btw, both instances are now the same version but it still isn't syncing, getting the same error
> 
> Could you please include the server log? That should contain more details about the failure.



sure, here it is:

```

(node:8306) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
DB size: 22728 KB
Becca (note cache) load took 12ms
App HTTP server starting up at port 8080
{
  "appVersion": "0.48.6",
  "dbVersion": 187,
  "syncVersion": 21,
  "buildDate": "2021-11-13T22:49:58+01:00",
  "buildRevision": "c94603010630cfafe64575ab378c482bb39fb083",
  "dataDirectory": "/Users/admin/Library/Application Support/trilium-data",
  "clipperProtocolVersion": "1.0"
}
CPU model: Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz, logical cores: 12 freq: 2600 Mhz
Listening on port 8080
Table counts: notes: 784, note_revisions: 1772, branches: 794, attributes: 339, api_tokens: 1
All consistency checks passed with no errors detected (took 37ms)
sync failed: Request to PUT http://****/api/sync/update failed, error: 500 Internal Server Error
stack: Error: Request to PUT http://****/api/sync/update failed, error: 500 Internal Server Error
    at generateError (/Users/admin/***/trilium/src/services/request.js:191:12)
    at ClientRequest.<anonymous> (/Users/admin/***/trilium/src/services/request.js:62:28)
    at ClientRequest.emit (events.js:314:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:640:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at Socket.socketOnData (_http_client.js:509:22)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:303:12)
    at readableAddChunk (_stream_readable.js:279:9)
    at Socket.Readable.push (_stream_readable.js:218:10)
ERROR: Failed to deserialize sync response: table entity_changes has no column named changeId

```

**Comment by zadam** [comment]
You're running an unreleased master branch version. That shouldn't be in any docker version (unless you've built it yourself)

**Comment by surajsharma** [comment]
> You're running an unreleased master branch version. That shouldn't be in any docker version (unless you've built it yourself)

nah, just cloned the repo from here and running it, the db is a few years old though

**Comment by zadam** [comment]
> nah, just cloned the repo from here

so you're running master. That's the problem.

**Comment by surajsharma** [comment]
> > nah, just cloned the repo from here
> 
> so you're running unreleased code from master branch. That's the problem, you should use only released versions.

so i downloaded the source from latest release and tried to run it (i can't run the electron app for some reason) and i got this:

`
ERROR: Current DB version 187 is newer than app db version 185 which means that it was created by newer and incompatible version of Trilium. Upgrade to latest version of Trilium to resolve this issue.
error: Forever detected script exited with code: 1
`

sorry to bother you with such trivial stuff i really am facing some issues here

**Comment by zadam** [comment]
DB version 187 is present only on unreleased master branch.

If you want to build from source, clone the git repo, switch to `stable` branch and there you won't have this problem.

**Comment by surajsharma** [comment]
> DB version 187 is present only on unreleased master branch.
> 
> If you want to build from source, clone the git repo, switch to `stable` branch and there you won't have this problem.

i did as you said, but getting the same error on `stable`

**Comment by zadam** [comment]
Ok, I realized this is a DB which you created when on master. You need to delete it since the older stable version doesn't work with the new DB format. Once you delete, start the app again, you will need to go through the setup process again and new DB will be created.

**Comment by surajsharma** [comment]
> Ok, I realized this is a DB which you created when on master. You need to delete it since the older stable version doesn't work with the new DB format. Once you delete, start the app again, you will need to go through the setup process again and new DB will be created.

won't i lose all my data if i delete the db?

**Comment by zadam** [comment]
If you exported the ZIP with notes from the old database, then you can import it into the new database (e.g. righclick in the note tree -> Import).

**Comment by surajsharma** [comment]
works, but now this https://github.com/zadam/trilium/issues/2384
