### ISSUE TITLE
(Bug report) Fails to import file when dragging and dropping

### ISSUE THREAD

**Issue by sigaloid** [TriliumNext/Trilium#2926]
### Trilium Version

0.52.3

### What operating system are you using?

Other Linux

### What is your setup?

Local + server sync

### Operating System Version

Fedora 36

### Description

```
JS Error: Cannot parse  into notes for drop
Stack: Error
    at N (http://127.0.0.1:37840/app-dist/desktop.js:2:103096)
    at Object.dragDrop (http://127.0.0.1:37840/app-dist/desktop.js:2:161296)
    at P.L (http://127.0.0.1:37840/libraries/fancytree/jquery.fancytree-all-deps.min.js:1:91573)
    at HTMLUListElement.dispatch (http://127.0.0.1:37840/libraries/jquery.min.js:2:43064)
    at HTMLUListElement.v.handle (http://127.0.0.1:37840/libraries/jquery.min.js:2:41048)
```

It seems like it depends where I drop it though because I dropped it in a different folder it seems to work okay.

**Comment by zadam** [comment]
Hi, is this reproducible? Based on the code and my testing, this happens when you drag some "non-file" draggable object onto the note. Could this be the case here?

**Comment by sigaloid** [comment]
It's reproducible in Sway WM (Wayland). However I couldn't record the problem with Wayland (OBS issue) so I switched back to i3 temporarily (X11) to record the issue. There, the issue didn't occur. I can only assume it's a Wayland bug with Chromium somehow.

**Comment by darkpoetry** [comment]
I am also getting this with PDF documents, mp3 files. I am also using Wayland. I'm using the NVIDIA proprietary drivers. The relevant errors are:
`JS Error: Cannot parse JSON '' into notes for drop
Stack: Error
    at C (http://127.0.0.1:37840/assets/v0.57.5/app-dist/desktop.js:2:96330)
    at Object.dragDrop (http://127.0.0.1:37840/assets/v0.57.5/app-dist/desktop.js:2:161891)
    at P.L (http://127.0.0.1:37840/assets/v0.57.5/libraries/fancytree/jquery.fancytree-all-deps.min.js:1:91573)
    at HTMLUListElement.dispatch (http://127.0.0.1:37840/assets/v0.57.5/libraries/jquery.min.js:2:43064)
    at HTMLUListElement.v.handle (http://127.0.0.1:37840/assets/v0.57.5/libraries/jquery.min.js:2:41048)`

**Comment by darkpoetry** [comment]
I'd also like to add that a similar non-response happens during drag and drop rearrangement of the document tree. Pretty much any mouse-driven action is foiled by this bug; somewhat randomly. 

Unfortunately the only video driver that works properly on all of my stuff is nvidia + wayland, and that is the general direction that window managers are headed in.

**Comment by darkpoetry** [comment]
One additional insight on this- if the drag+drop happens in the same monitor, it tends to work. Only if dragging from one monitor onto another monitor does it fail in recent testing.

**Comment by eliandoran** [comment]
I would expect the issue to be solved by now since we've upgraded Electron multiple versions. Let me know if it's still an issue.
