### ISSUE TITLE
(Bug report) Fail to load after deleting note

### ISSUE THREAD

**Issue by remygrandin** [TriliumNext/Trilium#2950]
### Trilium Version

Unsure, relatively recent, installed like 1 month ago

### What operating system are you using?

Other (specify below)

### What is your setup?

Server access only

### Operating System Version

Client : Edge Bowser | server : docker image

### Description

I was moving the example todo note elsewhere in the tree and as I deleted the exemple subnotes to have it clean and usable, trillium froze and now fail to load. In the console I get the error : 

```
Uncaught (in promise) Error: Branch "wXbHfbYf5lHh" has no note "cefMrK2NgmI4"
    at NoteTreeWidget.prepareNode (note_tree.js:626:19)
    at NoteTreeWidget.prepareChildren (note_tree.js:580:31)
    at NoteTreeWidget.prepareNode (note_tree.js:650:34)
    at NoteTreeWidget.prepareChildren (note_tree.js:580:31)
    at NoteTreeWidget.prepareNode (note_tree.js:650:34)
    at NoteTreeWidget.prepareChildren (note_tree.js:580:31)
    at NoteTreeWidget.prepareNode (note_tree.js:650:34)
    at NoteTreeWidget.prepareChildren (note_tree.js:580:31)
    at NoteTreeWidget.prepareNode (note_tree.js:650:34)
    at NoteTreeWidget.prepareRootNode (note_tree.js:548:21)
```

Is there a way I can locate and remediate the data or should I give up and restore my last full backup of the container data ?

**Comment by cednore** [comment]
I am experiencing this issue as well.
![image](https://user-images.githubusercontent.com/7719701/176864744-d979a853-70de-42e8-8ca3-52d3151c9d04.png)

**Comment by zadam** [comment]
@cednore does application restart help? Which version are you using?

**Comment by cednore** [comment]
@zadam Restarting didn't helped me. Unfortunately, I've removed whole data directory 'cause it was brand new with a few scribbles. Next time this happens, I will provide you more context. Version is `0.52.3`

**Comment by cednore** [comment]
@zadam I faced this issue again and fixed by restarting the app container. Thanks.

cc @remygrandin

**Comment by eliandoran** [comment]
Closing as stale.
