### ISSUE TITLE
Cannot write to trilium

### ISSUE THREAD

**Issue by amar-g72** [TriliumNext/Trilium#2975]
For bug reports, **PLEASE mention version of Trilium you're using** and also include **log files** from following location:

* `/home/[user]/.local/share/trilium-data/log` for Linux

OS: Debian 11.4
Trilium version: 0.53.4
Installation method: Pure Docker

JS Error: Error when calling PUT notes/XgqD2rooT2kl/change-title: error -

Stack: Error

at Object.logError ([https://trilium.mydomain.com/app/services/ws.js:1:621](https://trilium.gandhicloud.com/app/services/ws.js:1:621))

at Object.throwError ([https://trilium.mydomain.com/app/services/toast.js:20:33](https://trilium.gandhicloud.com/app/services/toast.js:20:33))

at reportError ([https://trilium.mydomain.com/app/services/server.js:15:229](https://trilium.gandhicloud.com/app/services/server.js:15:229))

at async Object.error ([https://trilium.mydomain.com/app/services/server.js:16:435](https://trilium.gandhicloud.com/app/services/server.js:16:435))

Error: Router not found for request /api/notes/XgqD2rooT2kl/change-title

at /usr/src/app/src/app.js:77:17

at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)

at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:328:13)

at /usr/src/app/node_modules/express/lib/router/index.js:286:9

at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:346:12)

at next (/usr/src/app/node_modules/express/lib/router/index.js:280:10)

at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:91:12)

at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:328:13)

at /usr/src/app/node_modules/express/lib/router/index.js:286:9

at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:346:12) {

status: 404

}

}

**Comment by zadam** [comment]
Hi, I don't recognize this error. Do you have some reverse proxy or something between the client and server? It looks like something is blocking the requests.

**Comment by Minituff** [comment]
I have this error too. It only happened after updating to 0.54. I reverted back to 0.52 (after restoring the old database) and I am still getting the error.

I am running Trilium in my home lab and using Cloudflare Tunnels and Cloudflare Access to only allow authorized users.
I would be happy to help troubleshoot if we can figure out what's going on. Im guessing its a Cloudflare config issue and not a Trilium issue.

<img width="346" alt="Screen Shot 2022-08-08 at 12 08 27 PM" src="https://user-images.githubusercontent.com/8152401/183495125-a5dead84-04a7-4a88-82b0-8c71b92881d1.png">

**Comment by amar-g72** [comment]
Hi,
How have you configured cloudflare, I thought it could have been because I
did it as a normal install rather than a docker install as I use it for
nextcloud as well.

**Comment by eliandoran** [comment]
Closing as stale and since it seems to be related to the environment and not Trilium itself.
