### ISSUE TITLE
(Bug report) Click on internal link button does nothing

### ISSUE THREAD

**Issue by mate1213** [TriliumNext/Trilium#3835]
### Trilium Version

latest docker image

### What operating system are you using?

Other (specify below)

### What is your setup?

RPi4 8GB

### Operating System Version

Ubuntu 22.04 LTS arm with docker

### Description

I cannot create internal links to other note. (Sorry it's an hungarian note.)
![image](https://user-images.githubusercontent.com/36986834/231473722-ac7ca2bf-9bd7-4f16-9114-dee517e896c1.png)
If I click on the tirilium icon nothing happens on UI, only the error below appears in the log.

Docker-compose file:
`version: '3.8'
networks:
    macnet:
      name: macnet

services:
    trilium:
        image: zadam/trilium:latest
        container_name: trilium
        restart: unless-stopped
        #ports:
        #    - "631:631"
        volumes:
          - './trilium-data:/home/node/trilium-data'
        networks:
          macnet:
            ipv4_address: 172.20.0.73
        dns:
          - 172.20.0.67
          - 172.20.0.1`

### Error logs

Error: Router not found for request /node_modules/@excalidraw/excalidraw/dist//dist/excalidraw-assets/Virgil.woff2
    at /usr/src/app/src/app.js:94:17
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:328:13)
    at /usr/src/app/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:346:12)
    at next (/usr/src/app/node_modules/express/lib/router/index.js:280:10)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:91:12)
    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:328:13)
    at /usr/src/app/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:346:12) {
  status: 404
}

**Comment by zadam** [comment]
Hello, unfortunately I can't reproduce this. What you showed is the backend log, could you check also for errors in the browsers console, e.g.:

![Uploading image.png…]()

**Comment by mate1213** [comment]
Hi! I could check it at the weekend. But in my case it's a win11 with latest firefox. On an HP laptop with touchscreen. (The inputs coming from regular touchpad and keyboard, in my scenario those where not used.)
I will check the logs ASAP-

**Comment by mate1213** [comment]
Hi!

I made the requested testing, I'm certain its a problem on the client side (Win11) because with Win 10 same Firefox version, there no problem.

![image](https://user-images.githubusercontent.com/36986834/233769567-2fbc621b-0080-4bab-bcde-d1a7b27a2e2c.png)
Here is the console output. 
I will try to help further if I can

**Comment by zadam** [comment]
Hmm, unfortunately no error is visible :-(

**Comment by eliandoran** [comment]
Should work just fine now.
