### ISSUE TITLE
(Bug report) After update to 0.59.x, desktop install has blank window - ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by sizer99** [TriliumNext/Trilium#3869]
### Trilium Version

0.59.4

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 11 Pro 22H2

### Description

After upgrading to 0.59.4 I get a blank Trilium window.  Running in command line shows that the server doesn't seem to start (or at least refusing connections) so client has nothing to show.  I added trilium.exe to Windows Defender Firewall, then just turned Windows Defender Firewall off entirely just in case that was the problem.

I went back to 59.3, 59.2, 59.1, they all have the problem.  Can no longer go back to 58.x because it says the current DB version (213) is newer than app version (212).

I am running with '--disable-gpu' and '--trace-warnings'.  (Is there a list of startup options somewhere I might use to get more info? --help does nothing.)

I tried going to  http://127.0.0.1:37840/ and  http://127.0.0.1:37840/login in my browser and got 'unable to connect'.

```
C:\news\trilium-windows-x64-0.59.4>trilium.exe --disable-gpu --trace-warnings --help

C:\news\trilium-windows-x64-0.59.4>
DB size: 2355 KB
Trusted reverse proxy: false
App HTTP server starting up at port 37840
{
  "appVersion": "0.59.4",
  "dbVersion": 213,
  "syncVersion": 29,
  "buildDate": "2023-04-17T21:40:35+02:00",
  "buildRevision": "1d3272e9f8c27106a66227fbb580677ae5d70427",
  "dataDirectory": "C:\\Users\\sizer\\AppData\\Roaming\\trilium-data",
  "clipperProtocolVersion": "1.0",
  "utcDateTime": "2023-04-23T02:22:46.053Z"
}
CPU model: AMD Ryzen 9 5900X 12-Core Processor            , logical cores: 24 freq: 3693 Mhz
Listening on port 37840
Becca (note cache) load took 3ms
Registered global shortcut Ctrl+Alt+P for action createNoteIntoInbox
(node:7060) electron: Failed to load URL: http://127.0.0.1:37840/ with error: ERR_CONNECTION_REFUSED
(Use `trilium --trace-warnings ...` to show where the warning was created)
[7060:0422/192248.895:ERROR:interface_endpoint_client.cc(658)] Message 0 rejected by interface blink.mojom.WidgetHost
Table counts: notes: 123, note_revisions: 227, branches: 125, attributes: 157, etapi_tokens: 0
All consistency checks passed with no errors detected (took 6ms)
```

Doing a ctrl-R from the blank window, I get this in the command window:
```
(node:7060) electron: Failed to load URL: http://127.0.0.1:37840/ with error: ERR_ADDRESS_INVALID
```

The trilium-data\log\trlilium-2023-04-22.log doesn't show any errors, but I'll attach it. too.

Thanks!

UPDATE:  I got it to 'work' through a complete hack I don't understand, see my next reply.

### Error logs

18:28:26.450 DB size: 2355 KB
18:28:27.188 Trusted reverse proxy: false
18:28:27.188 App HTTP server starting up at port 37840
18:28:27.189 {
  "appVersion": "0.59.3",
  "dbVersion": 213,
  "syncVersion": 29,
  "buildDate": "2023-03-27T23:06:14+02:00",
  "buildRevision": "9881e6de3e4966af39ec6245562dca6ac7b25eaa",
  "dataDirectory": "C:\\Users\\sizer\\AppData\\Roaming\\trilium-data",
  "clipperProtocolVersion": "1.0",
  "utcDateTime": "2023-04-23T01:28:26.449Z"
}
18:28:27.189 CPU model: AMD Ryzen 9 5900X 12-Core Processor            , logical cores: 24 freq: 3693 Mhz
18:28:27.197 Listening on port 37840
18:28:27.201 Becca (note cache) load took 3ms
18:28:27.419 Registered global shortcut Ctrl+Alt+P for action createNoteIntoInbox
18:28:31.204 Table counts: notes: 123, note_revisions: 227, branches: 125, attributes: 157, etapi_tokens: 0
18:28:31.220 All consistency checks passed with no errors detected (took 17ms)
18:29:03.893 DB size: 2355 KB
18:29:04.459 Trusted reverse proxy: false
18:29:04.459 App HTTP server starting up at port 37840
18:29:04.459 {
  "appVersion": "0.59.3",
  "dbVersion": 213,
  "syncVersion": 29,
  "buildDate": "2023-03-27T23:06:14+02:00",
  "buildRevision": "9881e6de3e4966af39ec6245562dca6ac7b25eaa",
  "dataDirectory": "C:\\Users\\sizer\\AppData\\Roaming\\trilium-data",
  "clipperProtocolVersion": "1.0",
  "utcDateTime": "2023-04-23T01:29:03.892Z"
}
18:29:04.460 CPU model: AMD Ryzen 9 5900X 12-Core Processor            , logical cores: 24 freq: 3693 Mhz
18:29:04.468 Listening on port 37840
18:29:04.471 Becca (note cache) load took 3ms
18:29:04.619 Registered global shortcut Ctrl+Alt+P for action createNoteIntoInbox
18:29:08.485 Table counts: notes: 123, note_revisions: 227, branches: 125, attributes: 157, etapi_tokens: 0
18:29:08.492 All consistency checks passed with no errors detected (took 7ms)
18:30:58.323 DB size: 2355 KB
18:30:58.898 Trusted reverse proxy: false
18:30:58.898 App HTTP server starting up at port 37840
18:30:58.898 {
  "appVersion": "0.59.3",
  "dbVersion": 213,
  "syncVersion": 29,
  "buildDate": "2023-03-27T23:06:14+02:00",
  "buildRevision": "9881e6de3e4966af39ec6245562dca6ac7b25eaa",
  "dataDirectory": "C:\\Users\\sizer\\AppData\\Roaming\\trilium-data",
  "clipperProtocolVersion": "1.0",
  "utcDateTime": "2023-04-23T01:30:58.322Z"
}
18:30:58.899 CPU model: AMD Ryzen 9 5900X 12-Core Processor            , logical cores: 24 freq: 3693 Mhz
18:30:58.907 Listening on port 37840
18:30:58.910 Becca (note cache) load took 3ms
18:30:59.061 Registered global shortcut Ctrl+Alt+P for action createNoteIntoInbox
18:31:02.912 Table counts: notes: 123, note_revisions: 227, branches: 125, attributes: 157, etapi_tokens: 0
18:31:02.918 All consistency checks passed with no errors detected (took 7ms)
18:35:58.942 Created backup at C:\Users\sizer\AppData\Roaming\trilium-data\backup/backup-daily.db
18:37:15.679 DB size: 2355 KB
18:37:16.245 Trusted reverse proxy: false
18:37:16.245 App HTTP server starting up at port 37840
18:37:16.245 {
  "appVersion": "0.59.3",
  "dbVersion": 213,
  "syncVersion": 29,
  "buildDate": "2023-03-27T23:06:14+02:00",
  "buildRevision": "9881e6de3e4966af39ec6245562dca6ac7b25eaa",
  "dataDirectory": "C:\\Users\\sizer\\AppData\\Roaming\\trilium-data",
  "clipperProtocolVersion": "1.0",
  "utcDateTime": "2023-04-23T01:37:15.678Z"
}
18:37:16.245 CPU model: AMD Ryzen 9 5900X 12-Core Processor            , logical cores: 24 freq: 3693 Mhz
18:37:16.253 Listening on port 37840
18:37:16.257 Becca (note cache) load took 3ms
18:37:16.425 Registered global shortcut Ctrl+Alt+P for action createNoteIntoInbox
18:37:20.258 Table counts: notes: 123, note_revisions: 227, branches: 125, attributes: 157, etapi_tokens: 0
18:37:20.264 All consistency checks passed with no errors detected (took 6ms)
18:51:46.234 DB size: 2355 KB
18:51:46.795 Trusted reverse proxy: false
18:51:46.796 App HTTP server starting up at port 37840
18:51:46.796 {
  "appVersion": "0.59.3",
  "dbVersion": 213,
  "syncVersion": 29,
  "buildDate": "2023-03-27T23:06:14+02:00",
  "buildRevision": "9881e6de3e4966af39ec6245562dca6ac7b25eaa",
  "dataDirectory": "C:\\Users\\sizer\\AppData\\Roaming\\trilium-data",
  "clipperProtocolVersion": "1.0",
  "utcDateTime": "2023-04-23T01:51:46.233Z"
}
18:51:46.796 CPU model: AMD Ryzen 9 5900X 12-Core Processor            , logical cores: 24 freq: 3693 Mhz
18:51:46.803 Listening on port 37840
18:51:46.807 Becca (note cache) load took 3ms
18:51:46.961 Registered global shortcut Ctrl+Alt+P for action createNoteIntoInbox
18:51:50.810 Table counts: notes: 123, note_revisions: 227, branches: 125, attributes: 157, etapi_tokens: 0
18:51:50.816 All consistency checks passed with no errors detected (took 6ms)
18:56:16.551 DB size: 2355 KB
18:56:17.117 Trusted reverse proxy: false
18:56:17.118 App HTTP server starting up at port 37840
18:56:17.118 {
  "appVersion": "0.59.3",
  "dbVersion": 213,
  "syncVersion": 29,
  "buildDate": "2023-03-27T23:06:14+02:00",
  "buildRevision": "9881e6de3e4966af39ec6245562dca6ac7b25eaa",
  "dataDirectory": "C:\\Users\\sizer\\AppData\\Roaming\\trilium-data",
  "clipperProtocolVersion": "1.0",
  "utcDateTime": "2023-04-23T01:56:16.550Z"
}
18:56:17.118 CPU model: AMD Ryzen 9 5900X 12-Core Processor            , logical cores: 24 freq: 3693 Mhz
18:56:17.126 Listening on port 37840
18:56:17.130 Becca (note cache) load took 3ms
18:56:17.288 Registered global shortcut Ctrl+Alt+P for action createNoteIntoInbox
18:56:21.133 Table counts: notes: 123, note_revisions: 227, branches: 125, attributes: 157, etapi_tokens: 0
18:56:21.139 All consistency checks passed with no errors detected (took 7ms)
18:56:27.715 DB size: 2355 KB
18:56:28.270 Trusted reverse proxy: false
18:56:28.270 App HTTP server starting up at port 37840
18:56:28.270 {
  "appVersion": "0.59.3",
  "dbVersion": 213,
  "syncVersion": 29,
  "buildDate": "2023-03-27T23:06:14+02:00",
  "buildRevision": "9881e6de3e4966af39ec6245562dca6ac7b25eaa",
  "dataDirectory": "C:\\Users\\sizer\\AppData\\Roaming\\trilium-data",
  "clipperProtocolVersion": "1.0",
  "utcDateTime": "2023-04-23T01:56:27.714Z"
}
18:56:28.271 CPU model: AMD Ryzen 9 5900X 12-Core Processor            , logical cores: 24 freq: 3693 Mhz
18:56:28.278 Listening on port 37840
18:56:28.283 Becca (note cache) load took 4ms
18:56:28.426 Registered global shortcut Ctrl+Alt+P for action createNoteIntoInbox
18:56:32.286 Table counts: notes: 123, note_revisions: 227, branches: 125, attributes: 157, etapi_tokens: 0
18:56:32.293 All consistency checks passed with no errors detected (took 7ms)
18:56:46.636 DB size: 2355 KB
18:56:47.190 Trusted reverse proxy: false
18:56:47.191 App HTTP server starting up at port 37840
18:56:47.191 {
  "appVersion": "0.59.3",
  "dbVersion": 213,
  "syncVersion": 29,
  "buildDate": "2023-03-27T23:06:14+02:00",
  "buildRevision": "9881e6de3e4966af39ec6245562dca6ac7b25eaa",
  "dataDirectory": "C:\\Users\\sizer\\AppData\\Roaming\\trilium-data",
  "clipperProtocolVersion": "1.0",
  "utcDateTime": "2023-04-23T01:56:46.635Z"
}
18:56:47.191 CPU model: AMD Ryzen 9 5900X 12-Core Processor            , logical cores: 24 freq: 3693 Mhz
18:56:47.198 Listening on port 37840
18:56:47.202 Becca (note cache) load took 3ms
18:56:47.354 Registered global shortcut Ctrl+Alt+P for action createNoteIntoInbox
18:56:51.205 Table counts: notes: 123, note_revisions: 227, branches: 125, attributes: 157, etapi_tokens: 0
18:56:51.211 All consistency checks passed with no errors detected (took 7ms)
19:13:06.189 DB size: 2355 KB
19:13:06.744 Trusted reverse proxy: false
19:13:06.745 App HTTP server starting up at port 37840
19:13:06.745 {
  "appVersion": "0.59.4",
  "dbVersion": 213,
  "syncVersion": 29,
  "buildDate": "2023-04-17T21:40:35+02:00",
  "buildRevision": "1d3272e9f8c27106a66227fbb580677ae5d70427",
  "dataDirectory": "C:\\Users\\sizer\\AppData\\Roaming\\trilium-data",
  "clipperProtocolVersion": "1.0",
  "utcDateTime": "2023-04-23T02:13:06.188Z"
}
19:13:06.745 CPU model: AMD Ryzen 9 5900X 12-Core Processor            , logical cores: 24 freq: 3693 Mhz
19:13:06.753 Listening on port 37840
19:13:06.757 Becca (note cache) load took 3ms
19:13:06.927 Registered global shortcut Ctrl+Alt+P for action createNoteIntoInbox
19:13:10.759 Table counts: notes: 123, note_revisions: 227, branches: 125, attributes: 157, etapi_tokens: 0
19:13:10.766 All consistency checks passed with no errors detected (took 6ms)
19:13:17.807 DB size: 2355 KB
19:13:18.376 Trusted reverse proxy: false
19:13:18.376 App HTTP server starting up at port 37840
19:13:18.376 {
  "appVersion": "0.59.4",
  "dbVersion": 213,
  "syncVersion": 29,
  "buildDate": "2023-04-17T21:40:35+02:00",
  "buildRevision": "1d3272e9f8c27106a66227fbb580677ae5d70427",
  "dataDirectory": "C:\\Users\\sizer\\AppData\\Roaming\\trilium-data",
  "clipperProtocolVersion": "1.0",
  "utcDateTime": "2023-04-23T02:13:17.806Z"
}
19:13:18.377 CPU model: AMD Ryzen 9 5900X 12-Core Processor            , logical cores: 24 freq: 3693 Mhz
19:13:18.384 Listening on port 37840
19:13:18.388 Becca (note cache) load took 4ms
19:13:18.548 Registered global shortcut Ctrl+Alt+P for action createNoteIntoInbox
19:13:22.389 Table counts: notes: 123, note_revisions: 227, branches: 125, attributes: 157, etapi_tokens: 0
19:13:22.396 All consistency checks passed with no errors detected (took 7ms)
19:14:00.259 DB size: 2355 KB
19:14:00.817 Trusted reverse proxy: false
19:14:00.818 App HTTP server starting up at port 37840
19:14:00.818 {
  "appVersion": "0.59.4",
  "dbVersion": 213,
  "syncVersion": 29,
  "buildDate": "2023-04-17T21:40:35+02:00",
  "buildRevision": "1d3272e9f8c27106a66227fbb580677ae5d70427",
  "dataDirectory": "C:\\Users\\sizer\\AppData\\Roaming\\trilium-data",
  "clipperProtocolVersion": "1.0",
  "utcDateTime": "2023-04-23T02:14:00.258Z"
}
19:14:00.818 CPU model: AMD Ryzen 9 5900X 12-Core Processor            , logical cores: 24 freq: 3693 Mhz
19:14:00.826 Listening on port 37840
19:14:00.830 Becca (note cache) load took 4ms
19:14:00.996 Registered global shortcut Ctrl+Alt+P for action createNoteIntoInbox
19:14:04.832 Table counts: notes: 123, note_revisions: 227, branches: 125, attributes: 157, etapi_tokens: 0
19:14:04.838 All consistency checks passed with no errors detected (took 7ms)
19:21:15.018 DB size: 2355 KB
19:21:15.581 Trusted reverse proxy: false
19:21:15.582 App HTTP server starting up at port 37840
19:21:15.582 {
  "appVersion": "0.59.1",
  "dbVersion": 213,
  "syncVersion": 29,
  "buildDate": "2023-02-28T23:39:34+01:00",
  "buildRevision": "9eb3075f65af98bd8c4a8ca8cc241ae2ae05bfa9",
  "dataDirectory": "C:\\Users\\sizer\\AppData\\Roaming\\trilium-data",
  "clipperProtocolVersion": "1.0",
  "utcDateTime": "2023-04-23T02:21:15.018Z"
}
19:21:15.582 CPU model: AMD Ryzen 9 5900X 12-Core Processor            , logical cores: 24 freq: 3693 Mhz
19:21:15.589 Listening on port 37840
19:21:15.593 Becca (note cache) load took 3ms
19:21:15.739 Registered global shortcut Ctrl+Alt+P for action createNoteIntoInbox
19:21:19.594 Table counts: notes: 123, note_revisions: 227, branches: 125, attributes: 157, etapi_tokens: 0
19:21:19.601 All consistency checks passed with no errors detected (took 7ms)
19:21:24.547 DB size: 2355 KB
19:21:25.122 Trusted reverse proxy: false
19:21:25.122 App HTTP server starting up at port 37840
19:21:25.122 {
  "appVersion": "0.59.1",
  "dbVersion": 213,
  "syncVersion": 29,
  "buildDate": "2023-02-28T23:39:34+01:00",
  "buildRevision": "9eb3075f65af98bd8c4a8ca8cc241ae2ae05bfa9",
  "dataDirectory": "C:\\Users\\sizer\\AppData\\Roaming\\trilium-data",
  "clipperProtocolVersion": "1.0",
  "utcDateTime": "2023-04-23T02:21:24.546Z"
}
19:21:25.123 CPU model: AMD Ryzen 9 5900X 12-Core Processor            , logical cores: 24 freq: 3693 Mhz
19:21:25.131 Listening on port 37840
19:21:25.135 Becca (note cache) load took 3ms
19:21:25.278 Registered global shortcut Ctrl+Alt+P for action createNoteIntoInbox
19:21:29.137 Table counts: notes: 123, note_revisions: 227, branches: 125, attributes: 157, etapi_tokens: 0
19:21:29.144 All consistency checks passed with no errors detected (took 7ms)
19:22:05.560 DB size: 2355 KB
19:22:06.109 Trusted reverse proxy: false
19:22:06.109 App HTTP server starting up at port 37840
19:22:06.110 {
  "appVersion": "0.59.4",
  "dbVersion": 213,
  "syncVersion": 29,
  "buildDate": "2023-04-17T21:40:35+02:00",
  "buildRevision": "1d3272e9f8c27106a66227fbb580677ae5d70427",
  "dataDirectory": "C:\\Users\\sizer\\AppData\\Roaming\\trilium-data",
  "clipperProtocolVersion": "1.0",
  "utcDateTime": "2023-04-23T02:22:05.559Z"
}
19:22:06.110 CPU model: AMD Ryzen 9 5900X 12-Core Processor            , logical cores: 24 freq: 3693 Mhz
19:22:06.118 Listening on port 37840
19:22:06.122 Becca (note cache) load took 4ms
19:22:06.261 Registered global shortcut Ctrl+Alt+P for action createNoteIntoInbox
19:22:10.124 Table counts: notes: 123, note_revisions: 227, branches: 125, attributes: 157, etapi_tokens: 0
19:22:10.130 All consistency checks passed with no errors detected (took 6ms)
19:22:46.054 DB size: 2355 KB
19:22:46.606 Trusted reverse proxy: false
19:22:46.607 App HTTP server starting up at port 37840
19:22:46.607 {
  "appVersion": "0.59.4",
  "dbVersion": 213,
  "syncVersion": 29,
  "buildDate": "2023-04-17T21:40:35+02:00",
  "buildRevision": "1d3272e9f8c27106a66227fbb580677ae5d70427",
  "dataDirectory": "C:\\Users\\sizer\\AppData\\Roaming\\trilium-data",
  "clipperProtocolVersion": "1.0",
  "utcDateTime": "2023-04-23T02:22:46.053Z"
}
19:22:46.607 CPU model: AMD Ryzen 9 5900X 12-Core Processor            , logical cores: 24 freq: 3693 Mhz
19:22:46.614 Listening on port 37840
19:22:46.618 Becca (note cache) load took 3ms
19:22:46.755 Registered global shortcut Ctrl+Alt+P for action createNoteIntoInbox
19:22:50.620 Table counts: notes: 123, note_revisions: 227, branches: 125, attributes: 157, etapi_tokens: 0
19:22:50.626 All consistency checks passed with no errors detected (took 6ms)

**Comment by sizer99** [comment]
Update:  If I put --trace-warnings **only** and remove --disable-gpu, then it actually works!   Looks like there's a heisenbug where taking the time to output debug warnings makes the problem not happen?

Here's the console output for when it works:

```
C:\news\trilium-windows-x64-0.59.4>
DB size: 2355 KB
Trusted reverse proxy: false
App HTTP server starting up at port 37840
{
  "appVersion": "0.59.4",
  "dbVersion": 213,
  "syncVersion": 29,
  "buildDate": "2023-04-17T21:40:35+02:00",
  "buildRevision": "1d3272e9f8c27106a66227fbb580677ae5d70427",
  "dataDirectory": "C:\\Users\\sizer\\AppData\\Roaming\\trilium-data",
  "clipperProtocolVersion": "1.0",
  "utcDateTime": "2023-04-23T02:38:42.298Z"
}
CPU model: AMD Ryzen 9 5900X 12-Core Processor            , logical cores: 24 freq: 3693 Mhz
Listening on port 37840
Becca (note cache) load took 3ms
Registered global shortcut Ctrl+Alt+P for action createNoteIntoInbox
Generated CSRF token Vgfv5evj-KgsPy0BEYs3ecXkkwsM6pF8P2n8 with secret _csrf=EvtACi3unfMcfj_KOjiZKLBV; Path=/
[30964:0422/193843.119:ERROR:interface_endpoint_client.cc(658)] Message 0 rejected by interface blink.mojom.WidgetHost
200 GET /api/options with 5864 bytes took 1ms
200 GET /api/tree with 9324 bytes took 1ms
200 GET /api/keyboard-actions with 12183 bytes took 0ms
200 GET /api/script/widgets with 2687 bytes took 1ms
200 POST /api/tree/load with 4159 bytes took 0ms
websocket client connected
Error: Router not found for request /images/icon-grey.png
    at C:\news\trilium-windows-x64-0.59.4\resources\app.asar\src\app.js:94:17
    at Layer.handle [as handle_request] (C:\news\trilium-windows-x64-0.59.4\resources\app.asar\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\news\trilium-windows-x64-0.59.4\resources\app.asar\node_modules\express\lib\router\index.js:328:13)
    at C:\news\trilium-windows-x64-0.59.4\resources\app.asar\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\news\trilium-windows-x64-0.59.4\resources\app.asar\node_modules\express\lib\router\index.js:346:12)
    at next (C:\news\trilium-windows-x64-0.59.4\resources\app.asar\node_modules\express\lib\router\index.js:280:10)
    at Layer.handle [as handle_request] (C:\news\trilium-windows-x64-0.59.4\resources\app.asar\node_modules\express\lib\router\layer.js:91:12)
    at trim_prefix (C:\news\trilium-windows-x64-0.59.4\resources\app.asar\node_modules\express\lib\router\index.js:328:13)
    at C:\news\trilium-windows-x64-0.59.4\resources\app.asar\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\news\trilium-windows-x64-0.59.4\resources\app.asar\node_modules\express\lib\router\index.js:346:12) {
  status: 404
}
200 GET /api/keyboard-shortcuts-for-notes with 2 bytes took 0ms
200 POST /api/tree/load with 6048 bytes took 0ms
200 POST /api/tree/load with 18360 bytes took 0ms
200 GET /api/notes/QeoD2uyZkxuF with 11082 bytes took 0ms
200 GET /api/note-map/QeoD2uyZkxuF/backlink-count with 11 bytes took 0ms
200 GET /api/script/startup with 2 bytes took 1ms
Table counts: notes: 123, note_revisions: 227, branches: 125, attributes: 157, etapi_tokens: 0
All consistency checks passed with no errors detected (took 6ms)
```

**Comment by soulsands** [comment]
Having no clue to the problem, but there is a backup generated at 'trilium-data/backup/backup-before-migration.db' after upgrading, you can restore it if necessary.

**Comment by sizer99** [comment]
Thanks! For now the --trace-warnings hack is working, so I'm running with 0.59.4 (and got a root export), but that'll be a fallback if necessary.

**Comment by renyuneyun** [comment]
I'm experiencing the same blank window issue since yesterday as well. I did nothing special but only restarted my laptop, and it happened.
I'm on archlinux, with trilium 0.62.4 (installed from the [trilium-bin AUR package](https://aur.archlinux.org/packages/trilium-bin)).

Unfortunately the trick above did not help (I also tried, e.g., `--disable-gpu` only). I do have server synchronization, but would love to hear any potential solution without having to clear my local installation in case something is not synced yet.

Console messages are:
```
❯ trilium --trace-warnings        
DB size: 410886 KB
{
  "appVersion": "0.62.4",
  "dbVersion": 227,
  "syncVersion": 31,
  "buildDate": "2023-12-07T00:03:59+01:00",
  "buildRevision": "2e23c521c356c2305124f5df0f474532fa5f34ce",
  "dataDirectory": "/home/ryey/.local/share/trilium-data",
  "clipperProtocolVersion": "1.0",
  "utcDateTime": "2024-01-07T23:07:11.220Z"
}
CPU model: 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz, logical cores: 8 freq: 3684 Mhz
Trusted reverse proxy: false
App HTTP server starting up at port 37840
Listening on port 37840
Becca (note cache) load took 48ms
Keyboard action showNoteInfo found in database, but not in action definition.
Keyboard action showLinkMap found in database, but not in action definition.
Keyboard action showNoteRevisions found in database, but not in action definition.
Keyboard action focusOnAttributes found in database, but not in action definition.
Keyboard action toggleZenMode found in database, but not in action definition.
Keyboard action forceSaveNoteRevision found in database, but not in action definition.
Registered global shortcut Ctrl+Alt+P for action createNoteIntoInbox
Generated CSRF token aSAFxTGD-2eS3LEbvdVPSAUYOjAaeDakRliM with secret _csrf=vZDxptM3MxOaxjYGhS4-f1jj; Path=/
[127409:0107/230712.097615:ERROR:interface_endpoint_client.cc(697)] Message 0 rejected by interface blink.mojom.WidgetHost

(trilium:127409): LIBDBUSMENU-GLIB-WARNING **: 23:07:12.125: About to Show called on an item wihtout submenus.  We're ignoring it.

(trilium:127409): LIBDBUSMENU-GLIB-WARNING **: 23:07:12.141: About to Show called on an item wihtout submenus.  We're ignoring it.
Table counts: notes: 3790, revisions: 2100, attachments: 1500, branches: 3900, attributes: 2128, etapi_tokens: 0, blobs: 4972
All consistency checks passed with no errors detected (took 84ms)
[127449:0107/230716.105131:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
Nothing to push
Finished pull
Nothing to push
Content hash computation took 43ms
Content hash checks PASSED
Sending message to all clients: {"type":"sync-finished","lastSyncedPush":1223622}
```

**Comment by zadam** [comment]
@renyuneyun given that arch is a rolling distro, could this be caused by some lib upgrade?

**Comment by renyuneyun** [comment]
@zadam Thanks for the reply. No, I did not perform system updates or (cascaded) package installation during the period. (The only installation I performed was for adding a single package, not updating or changing any existing ones.)
The only thing I can remember is that I restarted the laptop due to hang-up (caused by KDE lock screen). Trilium was running, indeed, but I presume that shouldn't be a problem (and I have done this quite a few times)?

**Comment by renyuneyun** [comment]
After a recent full-system update (two weeks ago), this went away.
Probably it's due to some dependencies.

**Comment by renyuneyun** [comment]
The bot does not seem to capture the discussion here completely. The issue happens both on **Windows** and Linux (e.g., in my case, archlinux). Windows has nothing to do with its explanation.

Also, this happens on MacOS as well for me. Every time this happens, I had to get a different build (simply removing existing one and replacing with the same version won't work). There should not be the same issue as on Windows (due to firewall as suspected by OP?).

**Comment by eliandoran** [comment]
@renyuneyun , are you having this issue on the latest release (v0.97.2)?

In the older versions there was an issue in which the Electron application would start faster than the server, which meant that it could not access the page to display. This has been solved some versions ago.

If you're still having issues, are you by any chance testing nightly versions or manual builds? This can mess with the cache.

**Comment by renyuneyun** [comment]
@eliandoran Thanks for the suggestion.

No, it has not yet happened for me for the latest release (v0.97.2). The issue happened quite randomly for me -- the same build and same system version/status may work for quite some time (weeks or months), but suddenly Trilium becomes blank one day, and stays blank thereafter.

I can report back after a while.


---

## Some details on when this happened

I can't recall all details, but remember the case for macOS clearly, as there were fewer updates (compared to on archlinux):

1. I was using Trilium (not TriliumNext), happily for quite a while.
2. It became blank one day, without any major system updates.
3. I switched to TriliumNext (because I already had this experience before on linux), and it worked correctly for a while. I even remember at that time, I did not go straight to the latest version because my sync server was not updated; I also struggled for getting old builds to work on macOS due to signature issues. TriliumNext was still a separate project by then.
4. Some time later, again without any major system updates, it became blank one day.
5. I downloaded the latest Trilium(Next), and it worked. Now TriliumNext became Trilium already; as a result, my `/applications` has three Trilium-related things: `trilium-mac-x64/`, `TriliumNext Notes.app` and `Trilium Notes.app`. Neither one of the first two works at this stage.

**Comment by eliandoran** [comment]
@renyuneyun , thanks for the detailed information.

I suspect you were running into two distinct issues:

* One caused by an incompatibility between macOS and the Electron version used in the old Trilium. This probably got fixed by an update to the Electron version.
* One caused by a race condition between the server and the desktop loading, which was fixed in the last few versions.

Feel free to reopen the bug if it reoccurs.
