### ISSUE TITLE
SqliteError: database is locked during startup using a smb share as a docker volume

### ISSUE THREAD

**Issue by tdsotm** [TriliumNext/Trilium#3987]
### Trilium Version

0.60-latest

### What operating system are you using?

Ubuntu

### What is your setup?

Local (no sync)

### Operating System Version

Windows 10

### Description

 I'm trying to setup following the official docker-compose yml file. At first data was being recreated each time I restarted the container. Then I setup the volume and I get an error during start.

My setup is as follows:

container mounts:

```
 "Mounts": [
            {
                "Type": "bind",
                "Source": "/home/infra/trilium/storage",
                "Destination": "/home/node/trilium-data",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
```

docker-compose.yml:

```
version: '2.1'

networks:
  proxy:
    external: true

services:
  trilium:
    image: zadam/trilium
    container_name: trilium
    restart: always
    ports:
      - "21800:8080"
    networks:
      proxy:
        ipv4_address: 172.20.0.14
    volumes:
      - ./storage:/home/node/trilium-data
```

container logs:

```
No USER_UID specified, leaving 1000
No USER_GID specified, leaving 1000
Generated session secret

/usr/src/app/node_modules/better-sqlite3/lib/methods/pragma.js:11
        return simple ? stmt.pluck().get() : stmt.all();
                                                  ^
SqliteError: database is locked
    at Database.pragma (/usr/src/app/node_modules/better-sqlite3/lib/methods/pragma.js:11:44)
    at Object.<anonymous> (/usr/src/app/src/services/sql.js:14:14)
    at Module._compile (node:internal/modules/cjs/loader:1191:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
    at Module.load (node:internal/modules/cjs/loader:1069:32)
    at Function.Module._load (node:internal/modules/cjs/loader:904:12)
    at Module.require (node:internal/modules/cjs/loader:1093:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/usr/src/app/src/services/notes.js:1:13)
    at Module._compile (node:internal/modules/cjs/loader:1191:14)
No USER_UID specified, leaving 1000
No USER_GID specified, leaving 1000
```

It is worth saying that the storage directory is actually a mounted smb share and files are persisted on the share:

```
ll storage/
total 28
drwxr-xr-x 2 root  root     0 May 31 04:33 ./
drwxrwxr-x 3 infra infra 4096 May 31 04:32 ../
-rwxr-xr-x 1 root  root     0 May 31 04:33 document.db*
drwxr-xr-x 2 root  root     0 May 31 04:33 log/
-rwxr-xr-x 1 root  root    64 May 31 04:33 session_secret.txt*
```

As you can see files were written/created on the share since the secret has a size != 0, so I'm not sure this is a share permission issue, but I don't know how to furhter troubleshoot this. Adding the share UID/GID makes no difference as I get the exact same behaviour. It also doesn't matter if I mount the smb share for the user running docker or not, the end result is still the same.

I have little experience with sqlite & js, I wouldn't know where to start debugging this issue and the error message is not helpful, at least not to me. 
What else can I try?

**Comment by tdsotm** [comment]
Hi, my server runs on docker on a ubuntu machine. My setup doesn't reach that spot, it fails after secret is generated.
