### ISSUE TITLE
Duration Plugin is not included for Day.js

### ISSUE THREAD

**Issue by BeatLink** [TriliumNext/Trilium#4456]
### Trilium Version

0.61.14

### What operating system are you using?

Other Linux

### What is your setup?

Local + server sync

### Operating System Version

Linux Mint Cinnamon

### Description

Trying to build a plugin but the following code throws an error

```javascript
var Duration = require('dayjs/plugin/Duration')
api.dayjs.extend(Duration)
```

### Error logs

```
11:09:23.739 JS Error: 500 POST /api/script/run/A8mPy7hVeuem - Load of script note "updateCalendarJson.js" (A8mPy7hVeuem) failed with: Cannot find module 'dayjs/plugin/Duration'
Require stack:
- /app/trilium/resources/app.asar/src/services/script_context.js
- /app/trilium/resources/app.asar/src/services/script.js
- /app/trilium/resources/app.asar/src/services/handlers.js
- /app/trilium/resources/app.asar/src/app.js
- /app/trilium/resources/app.asar/src/www
- /app/trilium/resources/app.asar/electron.js
- 
Stack: Error
    at Object.T [as logError] (http://127.0.0.1:37840/assets/v0.61.14/app-dist/desktop.js:2:115300)
    at Object.throwError (http://127.0.0.1:37840/assets/v0.61.14/app-dist/desktop.js:2:98113)
    at c (http://127.0.0.1:37840/assets/v0.61.14/app-dist/desktop.js:2:94837)
    at async EventEmitter.<anonymous> (http://127.0.0.1:37840/assets/v0.61.14/app-dist/desktop.js:2:94354)
```

**Comment by rauenzi** [comment]
Is this really a bug?

**Comment by BeatLink** [comment]
I thought all of the day.js plugins were included. Is that not the case?

**Comment by rauenzi** [comment]
As far as I can tell none are included or even intended to be included. Trilium only has the base library in the libraries folder.

**Comment by BeatLink** [comment]
Actually, in my plugins, ive been able to add at least 3 dayjs plugins like so:

```javascript
// Imports -----------------------------------------------------------------------------
var isBetween = require('dayjs/plugin/isBetween')
api.dayjs.extend(isBetween)

var advancedFormat = require('dayjs/plugin/advancedFormat')
api.dayjs.extend(advancedFormat)

var isSameOrBefore = require('dayjs/plugin/isSameOrBefore')
api.dayjs.extend(isSameOrBefore)
```

**Comment by rauenzi** [comment]
I leave it up to @zadam then but I see no mention of it in any of the api docs

**Comment by zadam** [comment]
There are many plugins available, none of them are loaded by default though. You seem to have found a good workaround @BeatLink

**Comment by BeatLink** [comment]
Thanks. For the duration plugin though, the above method doesnt work at all. It throws an error.

**Comment by BeatLink** [comment]
Hey. With modern versions of Trilium using the bundling tool, is it possible to include dayjs.duration in the core application for scripting purposes?

**Comment by eliandoran** [comment]
@BeatLink , the request is for backend or frontend scripts?

**Comment by BeatLink** [comment]
Both would be ideal if possible.
