### ISSUE TITLE
(Bug report) Application doesn't start (Migration Error)

### ISSUE THREAD

**Issue by cyber-mantis** [TriliumNext/Trilium#4492]
### Trilium Version

0.62.3

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 10 version 22H2 build 19045.3693

### Description

When trying to open Trilium, the process starts and then closes after a couple seconds, without opening a window. Opening it from command shows a migration error in the log. I got this error in all versions after 0.60.4, the one I currently use.

### Error logs

```
G:\trilium-windows-x64-0.62.3\trilium-windows-x64>
App db version is 227, while db version is 214. Migration needed.
DB size: 8183 KB
{
  "appVersion": "0.62.3",
  "dbVersion": 227,
  "syncVersion": 31,
  "buildDate": "2023-11-27T23:37:24+01:00",
  "buildRevision": "a6036859b8bd24be31dfcf6318e57cf696fa25bc",
  "dataDirectory": "C:\\Users\\[REDACTED]\\AppData\\Roaming\\trilium-data",
  "clipperProtocolVersion": "1.0",
  "utcDateTime": "2023-12-02T17:25:52.197Z"
}
CPU model: Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz, logical cores: 4 freq: 2394 Mhz
Trusted reverse proxy: false
App HTTP server starting up at port 37840
Listening on port 37840
Created backup at C:\Users\[REDACTED]\AppData\Roaming\trilium-data\backup/backup-before-migration-v060.db
Attempting migration to version 215
Migration with SQL script: CREATE TABLE IF NOT EXISTS "blobs" (
                                               `blobId` TEXT NOT NULL,
                                               `content`        TEXT NULL DEFAULT NULL,
                                               `dateModified` TEXT NOT NULL,
                                               `utcDateModified` TEXT NOT NULL,
                                               PRIMARY KEY(`blobId`)
);

ALTER TABLE notes ADD blobId TEXT DEFAULT NULL;
ALTER TABLE note_revisions ADD blobId TEXT DEFAULT NULL;

Migration to version 215 has been successful.
Attempting migration to version 216
Migration with JS module
ERROR: error during migration to version 216: SqliteError: database disk image is malformed
    at G:\trilium-windows-x64-0.62.3\trilium-windows-x64\resources\app.asar\src\services\sql.js:168:31
    at wrap (G:\trilium-windows-x64-0.62.3\trilium-windows-x64\resources\app.asar\src\services\sql.js:212:18)
    at Object.execute (G:\trilium-windows-x64-0.62.3\trilium-windows-x64\resources\app.asar\src\services\sql.js:168:12)
    at module.exports (G:\trilium-windows-x64-0.62.3\trilium-windows-x64\resources\app.asar\db\migrations\0216__move_content_into_blobs.js:24:17)
    at executeMigration (G:\trilium-windows-x64-0.62.3\trilium-windows-x64\resources\app.asar\src\services\migration.js:91:9)
    at Function.<anonymous> (G:\trilium-windows-x64-0.62.3\trilium-windows-x64\resources\app.asar\src\services\migration.js:59:17)
    at Function.sqliteTransaction (G:\trilium-windows-x64-0.62.3\trilium-windows-x64\resources\app.asar\node_modules\better-sqlite3\lib\methods\transaction.js:65:24)
    at Object.transactional (G:\trilium-windows-x64-0.62.3\trilium-windows-x64\resources\app.asar\src\services\sql.js:242:52)
    at migrate (G:\trilium-windows-x64-0.62.3\trilium-windows-x64\resources\app.asar\src\services\migration.js:54:9)
    at async Object.migrateIfNecessary (G:\trilium-windows-x64-0.62.3\trilium-windows-x64\resources\app.asar\src\services\migration.js:123:9)
ERROR: migration failed, crashing hard
The database connection is not open
TypeError: The database connection is not open
    at Function.sqliteTransaction (G:\trilium-windows-x64-0.62.3\trilium-windows-x64\resources\app.asar\node_modules\better-sqlite3\lib\methods\transaction.js:66:9)
    at Object.transactional (G:\trilium-windows-x64-0.62.3\trilium-windows-x64\resources\app.asar\src\services\sql.js:242:52)
    at migrate (G:\trilium-windows-x64-0.62.3\trilium-windows-x64\resources\app.asar\src\services\migration.js:54:9)
    at async Object.migrateIfNecessary (G:\trilium-windows-x64-0.62.3\trilium-windows-x64\resources\app.asar\src\services\migration.js:123:9)
    at async initDbConnection (G:\trilium-windows-x64-0.62.3\trilium-windows-x64\resources\app.asar\src\services\sql_init.js:41:5)
TypeError: The database connection is not open
    at Function.sqliteTransaction (G:\trilium-windows-x64-0.62.3\trilium-windows-x64\resources\app.asar\node_modules\better-sqlite3\lib\methods\transaction.js:66:9)
    at Object.transactional (G:\trilium-windows-x64-0.62.3\trilium-windows-x64\resources\app.asar\src\services\sql.js:242:52)
    at migrate (G:\trilium-windows-x64-0.62.3\trilium-windows-x64\resources\app.asar\src\services\migration.js:54:9)
    at async Object.migrateIfNecessary (G:\trilium-windows-x64-0.62.3\trilium-windows-x64\resources\app.asar\src\services\migration.js:123:9)
    at async initDbConnection (G:\trilium-windows-x64-0.62.3\trilium-windows-x64\resources\app.asar\src\services\sql_init.js:41:5)
```

**Comment by zadam** [comment]
Hello, this is a low level SQLite error which actually means the database is corrupted. The most common case is that people try to use e.g. Dropbox to sync the data and it corrupts the database.

One way to fix that would be restoring a backup, or perhaps trying to export the database as ZIP, reinstall Trilium and import the ZIP.

**Comment by zadam** [comment]
> Is there any way to do this correctly, without using network sync (since it's a single PC)?

When "syncing" this way, you need to make sure the Trilium process is killed. Basically the file can't be opened by the process for writing. I believe this way it should be safe, but it's still quite error-prone.

**Comment by deajan** [comment]
> > Is there any way to do this correctly, without using network sync (since it's a single PC)?
> 
> When "syncing" this way, you need to make sure the Trilium process is killed. Basically the file can't be opened by the process for writing. I believe this way it should be safe, but it's still quite error-prone.

You could also make snapshots before copying the script, either with Windows VSS, or with Linux lvm/zfs/btrfs/bcachefs.
