### ISSUE TITLE
(Bug report) Error occurred when create new notes under protected notes

### ISSUE THREAD

**Issue by qyqx** [TriliumNext/trilium#5259]
### TriliumNext Version

0.90.8

### What operating system are you using?

macOS

### What is your setup?

Local (no sync)

### Operating System Version

macOS Sonoma 14.5

### Description

<img width="552" alt="image" src="https://github.com/user-attachments/assets/d8d40cc0-3578-4138-bd7a-69be4c29b551">

It seems that empty content of "new notes" cause this error.

### Error logs
```
11:38:52.865 ERROR: get /api/notes/:noteId/blob threw exception: 'error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT', stack: Error: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT
    at Decipheriv.final (node:internal/crypto/cipher:193:29)
    at Object.decrypt (file:///Applications/TriliumNext%20Notes.app/Contents/Resources/app.asar/dist/src/services/encryption/data_encryption.js:55:91)
    at Object.decrypt (file:///Applications/TriliumNext%20Notes.app/Contents/Resources/app.asar/dist/src/services/protected_session.js:31:34)
    at processContent (file:///Applications/TriliumNext%20Notes.app/Contents/Resources/app.asar/dist/src/services/blob.js:27:73)
    at Object.getBlobPojo (file:///Applications/TriliumNext%20Notes.app/Contents/Resources/app.asar/dist/src/services/blob.js:20:24)
    at getNoteBlob (file:///Applications/TriliumNext%20Notes.app/Contents/Resources/app.asar/dist/src/routes/api/notes.js:16:24)
    at Function.cb (file:///Applications/TriliumNext%20Notes.app/Contents/Resources/app.asar/dist/src/routes/routes.js:378:34)
    at Function.sqliteTransaction (/Applications/TriliumNext Notes.app/Contents/Resources/app.asar/node_modules/better-sqlite3/lib/methods/transaction.js:65:24)
    at Object.transactional (file:///Applications/TriliumNext%20Notes.app/Contents/Resources/app.asar/dist/src/services/sql.js:205:52)
    at file:///Applications/TriliumNext%20Notes.app/Contents/Resources/app.asar/dist/src/routes/routes.js:379:44
11:38:52.865 200 GET /api/note-map/8AJxBYcgxGrG/backlink-count with 11 bytes took 0ms
11:38:52.869 JS Error: 500 GET /api/notes/8AJxBYcgxGrG/blob - error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT
Stack: Error
    at Object.b [as logError] (http://127.0.0.1:37840/assets/v0.90.8/app-dist/desktop.js:1:126937)
    at Object.g [as throwError] (http://127.0.0.1:37840/assets/v0.90.8/app-dist/desktop.js:1:116482)
    at l (http://127.0.0.1:37840/assets/v0.90.8/app-dist/desktop.js:1:113065)
    at async IpcRenderer.<anonymous> (http://127.0.0.1:37840/assets/v0.90.8/app-dist/desktop.js:1:112582)
11:38:52.972 204 PUT /api/options with 0 bytes took 1ms
```

**Comment by eliandoran** [comment]
Closing this as stale. Feel free to reopen if it's still the case.
