### ISSUE TITLE
Clipper causes exception

### ISSUE THREAD

**Issue by gerroon** [TriliumNext/Trilium#734]
I setup the clipper addon for Firefox last week, it used to work well until today.Now it is throwing exceptions in Trilium and refusing to clip a page.

I also set up the remote server successfully. I did some test when I set it upa and it worked. It also says it is connected on port 37840 in green in the clipper ui panel.

Clipper is added to Firefox 70 Linux

Trilium Linux 	0.37.6, DB version:	153

```
Content hash computation took 350ms
Content hash check for recent_notes FAILED. Local is CRQZRxVX/9Cuk/sb3Fk7tATH868=, remote is FrRHYvChAoCToEGiOjXal1UciUQ=
Trace: ERROR: Error executing transaction, executing rollback. Inner stack: TypeError: Cannot read property 'ext' of null
    at processImage (/usr/lib/trilium/resources/app.asar/src/services/image.js:22:25)
    at Object.saveImage (/usr/lib/trilium/resources/app.asar/src/services/image.js:54:41)
    at addImagesToNote (/usr/lib/trilium/resources/app.asar/src/routes/api/clipper.js:85:63)
    at createNote (/usr/lib/trilium/resources/app.asar/src/routes/api/clipper.js:62:36)
    at async /usr/lib/trilium/resources/app.asar/src/routes/routes.js:84:32
    at async /usr/lib/trilium/resources/app.asar/src/services/sql.js:201:19
Outside stack: Error
    at Object.transactional (/usr/lib/trilium/resources/app.asar/src/services/sql.js:192:23)
    at /usr/lib/trilium/resources/app.asar/src/routes/routes.js:83:38
    at /usr/lib/trilium/resources/app.asar/node_modules/cls-hooked/context.js:118:13
    at Namespace.run (/usr/lib/trilium/resources/app.asar/node_modules/cls-hooked/context.js:97:5)
    at Namespace.runAndReturn (/usr/lib/trilium/resources/app.asar/node_modules/cls-hooked/context.js:117:8)
    at Object.init (/usr/lib/trilium/resources/app.asar/src/services/cls.js:5:28)
    at /usr/lib/trilium/resources/app.asar/src/routes/routes.js:78:38
    at Layer.handle [as handle_request] (/usr/lib/trilium/resources/app.asar/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/lib/trilium/resources/app.asar/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/lib/trilium/resources/app.asar/node_modules/express/lib/router/route.js:112:3)
    at Object.error (/usr/lib/trilium/resources/app.asar/src/services/log.js:33:13)
    at /usr/lib/trilium/resources/app.asar/src/services/sql.js:210:21
Trace: ERROR: post /api/clipper/notes threw exception: TypeError: Cannot read property 'ext' of null
    at processImage (/usr/lib/trilium/resources/app.asar/src/services/image.js:22:25)
    at Object.saveImage (/usr/lib/trilium/resources/app.asar/src/services/image.js:54:41)
    at addImagesToNote (/usr/lib/trilium/resources/app.asar/src/routes/api/clipper.js:85:63)
    at createNote (/usr/lib/trilium/resources/app.asar/src/routes/api/clipper.js:62:36)
    at async /usr/lib/trilium/resources/app.asar/src/routes/routes.js:84:32
    at async /usr/lib/trilium/resources/app.asar/src/services/sql.js:201:19
    at Object.error (/usr/lib/trilium/resources/app.asar/src/services/log.js:33:13)
    at /usr/lib/trilium/resources/app.asar/src/routes/routes.js:97:17

```

**Comment by zadam** [comment]
To give some feedback on this - looks like this has been caused by an unrecognized image type. I will try to do some testing around this when I get to the clipper ..

**Comment by gerroon** [comment]
I also get this line right after the ones I posted above. 

```
TypeError: Cannot destructure property `noteId` of 'undefined' or 'null'.
    at sendPing (/usr/lib/trilium/resources/app.asar/src/services/ws.js:86:19)


```

**Comment by eliandoran** [comment]
Closing as stale.
